start_date: "2010-01-01"

EQUITIES:
  SP500: "^GSPC"
  NASDAQ100: "^NDX"
  DOWJONES: "^DJI"
  NIKKEI225: "^N225"
  FTSE100: "^FTSE"
  DAX40: "^GDAXI"
  NIFTY50: "^NSEI"

COMMODITIES:
  CRUDE_OIL: "CL=F"
  GOLD: "GC=F"
  SILVER: "SI=F"

FX:
  USDJPY: "JPY=X"
  EURUSD: "EURUSD=X"
  GBPUSD: "GBPUSD=X"
  USDCNY: "CNY=X"

VOL_BONDS:
  VIX: "^VIX"
  US10Y: "^TNX"


CRYPTO:
  BITCOIN: "BTC-USD"


